name: SCA

on:
  push:
    branches: ["main", "master"]

jobs:
  snyk-cli:
    uses: auth0/devsecops-tooling/.github/workflows/sca-scan.yml@main
    with:
      additional-arguments: ""
    secrets: inherit